config/routes.rb
MultipleUploadExample::Application.routes.draw do
  resources :albums

end

app/models/album.rb
class Album < ActiveRecord::Base
  has_many :photos, :dependent => :destroy
  accepts_nested_attributes_for :photos, :allow_destroy => true
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :album
  mount_uploader :image, ImageUploader

  def image=(val)
    unless val.is_a?(String)
      image_will_change!
      super
    end
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  # GET /albums
  # GET /albums.xml
  def index
    @albums = Album.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @albums }
    end
  end

  # GET /albums/1
  # GET /albums/1.xml
  def show
    @album = Album.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @album }
    end
  end

  # GET /albums/new
  # GET /albums/new.xml
  def new
    @album = Album.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @album }
    end
  end

  # GET /albums/1/edit
  def edit
    @album = Album.find(params[:id])
  end

  # POST /albums
  # POST /albums.xml
  def create
    @album = Album.new(params[:album])

    respond_to do |format|
      if @album.save
        format.html { redirect_to(@album, :notice => 'Album was successfully created.') }
        format.xml  { render :xml => @album, :status => :created, :location => @album }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @album.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /albums/1
  # PUT /albums/1.xml
  def update
    @album = Album.find(params[:id])

    respond_to do |format|
      if @album.update_attributes(params[:album])
        format.html { redirect_to(@album, :notice => 'Album was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @album.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.xml
  def destroy
    @album = Album.find(params[:id])
    @album.destroy

    respond_to do |format|
      format.html { redirect_to(albums_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_remove_fields(name, f)
    f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
  end

  def link_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    field = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to_function(name, "add_fields(this, '#{association}', '#{escape_javascript(field)}')")
  end
end

app/views/albums/_photo_fields.erb
<div class="field">
  <%= f.file_field :image %>
</div

app/views/albums/edit.html.erb
<h1>Editing album</h1>

<%= form_for @album, :html => {:multipart => true} do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>: <%= @album.name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= @album.description %>
  </div>

  <fieldset>
    <legend>Fotos</legend>
    <% if @album.photos.empty? %>
      Sem fotos...
    <% end %>
    <% f.fields_for :photos do |builder| %>
      <div class="field" style="float:left; margin-left:5px;">
        <%= image_tag builder.object.image.small.url %>
        <br />
        <%= link_to_remove_fields "Remover", builder %>
      </div>
    <% end %>
    <div style="clear:both;"></div>
    <%= link_to_add_fields "Adicionar", f, :photos %>
  </fieldset>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<h1>Listing albums</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @albums.each do |album| %>
  <tr>
    <td><%= album.name %></td>
    <td><%= album.description %></td>
    <td><%= link_to 'Show', album %></td>
    <td><%= link_to 'Edit', edit_album_path(album) %></td>
    <td><%= link_to 'Destroy', album, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Album', new_album_path %>

app/views/albums/new.html.erb
<h1>New album</h1>

<%= form_for @album, :html => {:multipart => true} do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>

  <% f.fields_for :photos do |builder| %>
    <% render 'photos', :f => builder %>
  <% end %>
  <%= link_to_add_fields "Adicionar", f, :photos %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', albums_path %>

<script language="javascript">
  function mark_default(radio) {
    $(".album_photo_default").each(function(index) {
      this.value = "false";
    });
    $(radio).prev("input[type^=hidden]")[0].value = "true";
  }
</script>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @album.name %>
</p>

<p>
  <b>Description:</b>
  <%= @album.description %>
</p>

<% for photo in @album.photos %>
<p>
  <%= image_tag photo.image.url %>
</p>
<% end %>


<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MultipleUploadExample</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>